### ISSUE TITLE
problem of model display 

### ISSUE THREAD

**Issue by zhaoxiaomiao** [kovacsv/Online3DViewer#101]
When I use the online 3D viewer on my website, I find that the effect and color of the model are wrong. The actual effect of the model is shown in Figure 1 below, while the effect on the online 3D viewer is shown in Figure 2
![1](https://user-images.githubusercontent.com/12390272/126659393-6ca0c714-7ff7-4add-b3de-f129512051e2.png)
![2](https://user-images.githubusercontent.com/12390272/126659406-b166c22b-8ada-4cd1-b98b-b207e2049159.png)
[A.zip](https://github.com/kovacsv/Online3DViewer/files/6863104/A.zip)

**Comment by kovacsv** [comment]
There are two things here:
- Red surfaces are probably red because you defined default color as red, and there is no material assigned in the file for these surfaces.
- The blue one is something I don't understand. Opening the file in the default 3D Viewer on Windows looks the same as on the website. What other viewer do you use?

![image](https://user-images.githubusercontent.com/2034315/126699834-c404363f-b3ab-435f-97c3-4452646d1ad4.png)

**Comment by zhaoxiaomiao** [comment]
> 这里有两件事：
> 
> * 红色曲面可能是红色的，因为您将默认颜色定义为红色，并且文件中没有为这些曲面指定材质。
> * 蓝色的是我不明白的东西。在 Windows 上的默认 3D 查看器中打开文件看起来与在网站上相同。你还使用什么其他查看器？
> 
> ![图像](https://user-images.githubusercontent.com/2034315/126699834-c404363f-b3ab-435f-97c3-4452646d1ad4.png)

Please view it on the website in the following way
![1](https://user-images.githubusercontent.com/12390272/126727752-d58652c8-0f50-49c5-88cb-6eeaf08b26f7.png)

**Comment by kovacsv** [comment]
Remove or modify the defaultcolor="200,0,0" parameter and it will look the same as in other viewers.
