### ISSUE TITLE
`IFC` import fails with error `Unexpected placement type`

### ISSUE THREAD

**Issue by hey24sheep** [kovacsv/Online3DViewer#135]
Try importing an `.ifc` file (download from [here](http://openifcmodel.cs.auckland.ac.nz/)) it fails.

Error 
`web-ifc-api.js:885 Unexpected profile type: 572779678 at 11639`

Error Image
![Capture](https://user-images.githubusercontent.com/31468022/132989855-e68a81bb-9d09-442e-a0b4-7c007145568a.PNG)

**Comment by kovacsv** [comment]
Wow, you have just found the hidden feature of opening IFC files. :)

It's in experimental phase, because [web-ifc](https://github.com/tomvandig/web-ifc) is still under heavy development. Please check if the official web-ifc example viewer can open your file, and if not, it's better to create an issue there.

**Comment by hey24sheep** [comment]
Issue is with `web-ifc`. I have opened an [issue](https://github.com/tomvandig/web-ifc/issues/83) there as well.

**Comment by kovacsv** [comment]
It's a web-ifc issue, so I close this one.
