### ISSUE TITLE
No importable file found.

### ISSUE THREAD

**Issue by quasiresearcher** [kovacsv/Online3DViewer#165]
Hi

I followed the guide (https://github.com/kovacsv/Online3DViewer/wiki/Use-the-Viewer-on-Your-Website) but ran into a problem. 

I meet 'No importable file found' error.

Could you take a look at my code(https://github.com/quasiresearcher/additive_monster ) if you have time and help me find a solution.

Thanks

**Comment by kovacsv** [comment]
Seems fine to me. The problem is probably that you are running the webpage locally, and not on a web server. In this case some calls are blocked by the CORS policy.

Try to run a local webserver, and it should work. If you haven't done this before, run the following commands:
```
npm install -g http-server
http-server
```

And then open localhost:8080 in your browser.

![image](https://user-images.githubusercontent.com/2034315/140318500-f39e2151-e41b-4a32-a9f8-b72b29f10ceb.png)

**Comment by quasiresearcher** [comment]
Thanks
