### ISSUE TITLE
canvas - background transparent 

### ISSUE THREAD

**Issue by wontroba666** [kovacsv/Online3DViewer#180]
Hello, I can't see it in the documentation - is it possible to set the background color of the canvas to a TRANSPARENT in the web version ?

**Comment by kovacsv** [comment]
At the moment it's not possible, because the WebGL context is initalized without alpha (alpha causes performance issues). On the other hand, you can set the background color to any color using the `backgroundcolor` attribute.

You can read the details here:
https://github.com/kovacsv/Online3DViewer/wiki/Use-the-Viewer-on-Your-Website

**Comment by kovacsv** [comment]
Duplicate: #286
