### ISSUE TITLE
Disable export options?

### ISSUE THREAD

**Issue by nirurin** [kovacsv/Online3DViewer#275]
I would like to use this setup to embed 3D models of things I have created on my website for my portfolio, however by default this gives an easy "export models" option which isn't ideal for some of my models as they aren't meant to be freely available for use. 

Would be nice to be able to just hide or disable the export model option, just to act as a barrier. (I know there are still ways to grab the model through other means, but they tend not to be easy for non-technically minded people). 

Alternatively - Add the ability to alter the css for the embed_logo maybe? I can hide this using browser inspect, but that won't work (I dont think) if I try it with local css because of it being in an iframe. I guess it might be possible if I self-host the whole engine but the instructions for that were.... baffling to me haha

**Comment by kovacsv** [comment]
Disabling export doesn't fit in the mindset of Online 3D Viewer. This is a free and open source project, and the message I'd like to send is to use open tools, and make your intellectual property available for everyone.

Hiding the logo during embedding raises some ethical questions (although I can't prevent you to do it), because embedding uses the main server's resources, but removing the logo hides the attribution to the original authors of the viewer.

I think that the best way to solve what you would like to do is to self-host the viewer. Let me know if the instructions are not straightforward enough, so I can improve them.

Instructions on embedding the engine:
https://github.com/kovacsv/Online3DViewer/wiki/Embed-the-Viewer-Engine

Example project that uses the npm package:
https://github.com/kovacsv/Online3DViewerExample

**Comment by nirurin** [comment]
The embed project example I don't understand... It says to run those
commands from the root of the directory, so do I download the directory? To
where? Windows? Linux server?

My website is a ghost cms install on a docker container, is the viewer
engine able to be installed on docker?

**Comment by kovacsv** [comment]
If you don't have basic NPM, ES6 and bundling knowledge than the easiest way to get the browser-ready package, copy it to the server, and then just include it in your site: https://github.com/kovacsv/Online3DViewer/wiki/Embed-the-Viewer-Engine#browser-ready-bundle.
