### ISSUE TITLE
can't load  files form server url

### ISSUE THREAD

**Issue by daviddu2020** [kovacsv/Online3DViewer#28]
Hello Kovacsv,  thanks for your great project!
Now I facing an issue, I build two web servers with windows IIS,  one for 3dviewer, one for file server, both of them work fine.
but while I thy to open below link, it pop up "No readable file found." Please help me how to troubleshooting.
![Snipaste_2020-09-14_11-32-38](https://user-images.githubusercontent.com/71243620/93041030-05181d00-f67e-11ea-9714-fb6745a129b1.png)
![Snipaste_2020-09-14_11-33-19](https://user-images.githubusercontent.com/71243620/93041057-1e20ce00-f67e-11ea-96e6-c8b289ed460c.png)

http://localhost/test/#http://localhost:83/adss/cube.3ds

**Comment by kovacsv** [comment]
Hi,

- One solution is to put the files next to the viewer (in a subfolder, for example), and something like this should work: https://3dviewer.net/#testfiles/cube.3ds
- If you want to use full urls, than the problem is usually with CORS. You have to enable Cross Origin Requests in your web server.

P.S.: The viewer wasn't tested on Internet Explorer.

**Comment by daviddu2020** [comment]
You are right, it was cause by CORS. It works good now! Thanks for your fast respond.

**Comment by kovacsv** [comment]
Cool! :)
