### ISSUE TITLE
Add orthographic camera

### ISSUE THREAD

**Issue by dgalvez15** [kovacsv/Online3DViewer#293]
Good morning,
thanks for sharing this amazing library! I am trying to change to camera ortographic but i don't know is possible. It's possible???

If is possible, working same perspective, eye (position), center(lookAt) and up ????

Thanks,
David

**Comment by Til-Piffl** [comment]
+1 from me!

I using your great 3dviewer to display technical systems and it would be very helpful if I could switch to a orthographic projection so that I could judge the alignment of elements in the system.

(I'm happy to make some changes myself, if you point me in the right direction)

Thanks,

Til

**Comment by kovacsv** [comment]
Planned in the next release. 🙂

**Comment by Til-Piffl** [comment]
Thanks, that's perfect!
