### ISSUE TITLE
Open local file via directory url

### ISSUE THREAD

**Issue by paireks** [kovacsv/Online3DViewer#315]
Hey @kovacsv! :)

Question is if it's possible to open viewer with local file, but not by drag and drop, but using directory to local file instead.

That would make it possible to create a button in another app that opens a web browser with Online 3D Viewer with already opened local file. Small thing, but would be amazing if it's possible to implement.

**Comment by kovacsv** [comment]
Hey @paireks,

I don't think it's possible. A website needs explicit permission from the user to access the file system (drag and drop, or file browser dialog). Otherwise it would be a big security issue if a website could just read files from your computer. 🙂

I have an idea for a while to compile a desktop application from the viewer using electron or something like that. It would make that workflow possible.

**Comment by paireks** [comment]
Ok, I see. Damn it 😄
