### ISSUE TITLE
Uncaught SyntaxError: expected expression, got keyword 'var'

### ISSUE THREAD

**Issue by callum-gander** [kovacsv/Online3DViewer#354]
For whatever reason, I've been getting the following error whenever I try to load a .3dm file into the 3D viewer but .stl's work fine
```
Uncaught SyntaxError: expected expression, got keyword 'var' 
``` 
The error is occurring in http://localhost:3000/libs/loaders/rhino3dm.min.js at line 181. I'm not really sure what's going on here if I'm honest, any idea?

**Comment by kovacsv** [comment]
What were you trying to do?

**Comment by callum-gander** [comment]
The same workflow I have for stls: load in the model into a viewer component, calculate the volume and the surface area and then tear down the component

**Comment by kovacsv** [comment]
I think it's because of the delay loading method the library uses. There are two ways for handling third-party libraries.
1. Some of them (like three.js, fflate, etc.) are bundled together with the rest of the engine.
2. Some of them (like rhino3dm, occt-import-js, etc.) are just provided as libraries in the `libs` folder.

The latter method is optimized for browser usage, they are loaded with this method.
```js
let scriptElement = document.createElement ('script');
scriptElement.type = 'text/javascript';
scriptElement.src = GetExternalLibPath (libName);
document.head.appendChild (scriptElement);
```

For these libs the engine uses the browser-ready bundles, so they work only in a browser environment. Are you trying to run the code in a browser or in a node.js environment?

**Comment by kovacsv** [comment]
The external lib location is probably fine, because it founds the `rhino3dm.min.js`. The only thing I can think of that maybe your server serves `js` files somehow differently. Do you see any suspicious messages in the console?

**Comment by callum-gander** [comment]
Figured it out, for whatever reason the rhino3dm.min.js didn't match the one included in the npm module. Not particularly sure how that happened but putting the one in the module resolved it
