### ISSUE TITLE
o3dv.website.min.js

### ISSUE THREAD

**Issue by tril-alex** [kovacsv/Online3DViewer#440]
Hello everyone. Could you tell me if there is a possibility to translate hints and buttons in this file o3dv.website.min.js to another language? How can I do it?

**Comment by rafael-vm** [comment]
Dear @tril-alex I did this to use the online 3d viewer in portuguese. I created a new js file in the source/website with a function which change the viewer names and denominations in dependence of the browser language. You can see the result in [htt](http://200.17.71.18/). If your browser language is pt-br it shows the viewer in Brazilian Portuguese, otherwise it shows in english.
I did create a fork/pull request to add this feature to the online3dviewer, but went deade without acceptance.
If you like it we can exchange info about how to do it. 
Best,

**Comment by tril-alex** [comment]
**Thanks for the help!!!**

**Comment by kovacsv** [comment]
Currently there is no easy way, I've added this ticket for supporting localization: #445.
